---
- name: Add people
  become: yes
  become_method: sudo
  tags: [ 'radical::people' ]
  hosts: radical
  tasks:
    - name: Add users
      user:
        name: "{{ item }}"
        groups: sudo
        state: present
      with_items:
        - marcidy
        - r
        - person
        - beka
        - astrid
        - star
        - lily

- name: Install Home Assistant
  become: yes
  become_method: sudo
  tags: [ 'radical::homeassistant' ]
  hosts: radical
  vars:
    homeassistant_config_repo: http://github.com/queeriouslabs/home_assistant_config.git
    homeassistant_version: 2024.3.2
  roles:
    - home_assistant

- name: Additional packages
  become: yes
  become_method: sudo
  tags: [ 'radical::additional_packages' ]
  hosts: radical
  tasks:
    - name: Install Additional Packages
      apt:
        name: "{{ deps }}"
      vars:
        deps:
          - tmux
