---
- name: Add people
  become: yes
  become_method: sudo
  tags: [ 'radical::people' ]
  hosts: radical
  tasks:
    - name: Add users
      user:
        name: "{{ item }}"
        groups: sudo
        state: present
      with_items:
        - marcidy
        - r
        - person
        - beka
        - astrid
        - star
        - lily

- name: Install Home Assistant
  become: yes
  become_method: sudo
  tags: [ 'radical::homeassistant' ]
  hosts: radical
  roles:
    - home_assistant
