---
all:
  hosts:
    radical:
      ansible_host: 192.168.56.105
      ansible_port: 22
      ansible_user: vagrant
      ansible_ssh_private_key_file: '../../.vagrant/machines/radical/virtualbox/private_key'
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
