---
homeassistant_version: 2025.2
homeassistant_user: homeassistant
homeassistant_basedir: /srv/homeassistant
homeassistant_venv: "{{ homeassistant_basedir }}/venv"
homeassistant_homedir: "{{ homeassistant_basedir }}/home"
homeassistant_systemd_unit_filename: home-assistant@{{ homeassistant_user }}.service
