---
- name: Install dependencies
  become: true
  become_method: sudo
  apt:
    name: "{{ deps }}"
  vars:
    deps:
      - python3 
      - python3-dev 
      - python3-venv 
      - python3-pip 
      - bluez 
      - libffi-dev 
      - libssl-dev 
      - libjpeg-dev 
      - zlib1g-dev 
      - autoconf 
      - build-essential 
      - libopenjp2-7 
      - libtiff6 
      - libturbojpeg0-dev 
      - tzdata 
      - ffmpeg 
      - liblapack3 
      - liblapack-dev
      - libatlas-base-dev
      - git

- name: Create Home Assistant group
  become: true
  become_method: sudo
  group:
    name: "{{ homeassistant_user }}"
    state: present

- name: Create Home Assistant user
  become: true
  become_method: sudo
  user:
    name: "{{ homeassistant_user }}"
    state: present
    group: "{{ homeassistant_user }}"
    system: yes

- name: Create directories
  become: true
  become_method: sudo
  file:
    path: "{{ item }}"
    owner: "{{ homeassistant_user }}"
    group: "{{ homeassistant_user }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ homeassistant_basedir }}"
    - "{{ homeassistant_basedir }}/systemd"
    - "{{ homeassistant_basedir }}/config_repo"
    - "{{ homeassistant_venv }}"

- name: recursive reown homeassistant directory
  become: true
  become_method: sudo
  file:
    path: "{{ homeassistant_basedir }}"
    state: directory
    recurse: yes
    owner: "{{ homeassistant_user }}"
    group: "{{ homeassistant_user }}"

- name: Check for .homeassistant directory
  stat:
    path: "/home/{{ homeassistant_user }}/.homeassistant"
  register: ha_config_dir

- name: Create blank .homeassistant directory if missing
  become: true
  become_method: sudo
  file:
    path: "/home/{{ homeassistant_user }}/.homeassistant"
    owner: "{{ homeassistant_user }}"
    group: "{{ homeassistant_user }}"
    state: directory
    mode: 0755
  when: ha_config_dir.stat.exists is false

- name: Deploy configuration repository
  become: true
  become_method: sudo
  become_user: "{{ homeassistant_user }}"
  git:
    force: true
    dest: "{{ homeassistant_basedir }}/config_repo"
    repo: "{{ homeassistant_config_repo }}"

- name: Create venv with upgraded pip
  become: true
  become_method: sudo
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: 1
  pip:
    name: pip
    state: latest
    virtualenv: "{{ homeassistant_venv }}"
    virtualenv_command: /usr/bin/python3 -m venv --copies {{ homeassistant_venv }}

- name: Install wheel
  become: true
  become_method: sudo
  command: "{{ homeassistant_venv }}/bin/python3 -m pip install wheel"

- name: Install homeassistant
  become: true
  become_method: sudo
  pip:
    name: homeassistant=={{ homeassistant_version }}
    virtualenv: "{{ homeassistant_venv }}"

- name: recursive reown homeassistant directory
  become: true
  become_method: sudo
  file:
    path: "{{ homeassistant_basedir }}"
    state: directory
    recurse: yes
    owner: "{{ homeassistant_user }}"
    group: "{{ homeassistant_user }}"

- name: Add convenience symlink to .homeassistant
  become: true
  become_method: sudo
  become_user: "{{ homeassistant_user }}"
  file:
    src: "/home/{{ homeassistant_user }}/.homeassistant"
    dest: "/home/{{ homeassistant_user }}/homeassistant"
    owner: "{{ homeassistant_user }}"
    group: "{{ homeassistant_user }}"
    state: link

- name: template out systemd unit file
  become: true
  become_method: sudo
  template:
    src: "{{ homeassistant_systemd_unit_filename }}.j2"
    dest: "{{ homeassistant_basedir }}/systemd/{{ homeassistant_systemd_unit_filename }}"
    owner: "{{ homeassistant_user }}"
    group: "{{ homeassistant_user }}"
    mode: '0644'

- name: link homeassistant unit file to /etc/systemd directory
  become: true
  become_method: sudo
  file:
    src: "{{ homeassistant_basedir }}/systemd/{{ homeassistant_systemd_unit_filename }}"
    dest: /etc/systemd/system/{{ homeassistant_systemd_unit_filename }}
    owner: root
    group: root
    state: link

- name: reload systemd and start home assistant
  become: true
  become_method: sudo
  systemd:
    name: "{{ homeassistant_systemd_unit_filename }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
